EXTRA_CFLAGS += -DWIFIPM_INI=0
EXTRA_CFLAGS += -DWIFIPM_DEBUG

obj-$(CONFIG_WIFIPM)	+= wifipm.o

obj-$(CONFIG_SHWLAN_BCM4329_1) += ../../../../system/wlan/broadcom/4.218_1/
obj-$(CONFIG_SHWLAN_BCM4330_1) += ../../../../system/wlan/broadcom/5.90_1/
